version: "3"

services:
  db:
    image: "mysql:5.7"
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor'
    volumes:
      - /var/lib/mysql57-data:/var/lib/mysql
  api:
    image: phimmoi:dev
    command: bash -c "bundle install && rake db:create db:migrate && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
    - db