default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("PUMA_MAX_THREADS") { 5 } %>
  username: root
  password: toor
  socket: /var/run/mysqld/mysqld.sock
  port: 3306
  host: db
development:
  <<: *default
  database: dev_database

production:
  <<: *default
  database: pro_database

test:
  <<: *default
  database: test_database